# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rabbitmq:3.12.9-management
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: false

serviceAccount:
  create: false

initContainers: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

configmap:
  enabled: true
  data:
    NOTIBROKER_PORT: "5672"

env:
  - name: RABBITMQ_DEFAULT_USER
    valueFrom:
      secretKeyRef:
        name: noti-broker
        key: NOTIBROKER_USER
  - name: RABBITMQ_DEFAULT_PASS
    valueFrom:
      secretKeyRef:
        name: noti-broker
        key: NOTIBROKER_PASS

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 15672
  additionalPorts:
    - port: 5672
      name: amqp

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: noti-broker.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}