FROM openjdk:17-jdk-alpine
MAINTAINER HungTran.com
COPY /target/MeetingTeam-0.0.1-SNAPSHOT.war MeetingTeam-0.0.1-SNAPSHOT.war
ENTRYPOINT ["java","-jar","MeetingTeam-0.0.1-SNAPSHOT.war"]
EXPOSE 587 8080