apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER:  cm9vdA==
  DB_PASS:  dHJhbnRpZW5odW5nLjEy