apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  STOMPBROKER_USER:  YWRtaW4=
  STOMPBROKER_PASS:  dHJhbnRpZW5odW5nLjEy