version: "3.8"
services:
  mysql-service:
    image: mysql
    container_name: mysql-service
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PORT: ${DB_PORT}
    volumes:
      - db:/var/lib/mysql
    networks:
      - meeting-team-network
  flyway-service:
    image: mt-flyway
    container_name: flyway-service
    environment:
      DB_HOST: mysql-service
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - meeting-team-network
  rabbitmq-service:
    image: rabbitmq:3.12.9-management
    container_name: rabbitmq-service
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - meeting-team-network
  backend-service:
    image: mt-backend
    container_name: backend-service
    depends_on:
        - mysql-service
        - noti-broker
        - stomp-broker
    ports: 
        - 8080:8080
    environment:
        DB_HOST: mysql-service
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_DATABASE: ${DB_DATABASE}
        RABBITMQ_HOST: rabbitmq-service
        RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
        RABBITMQ_STOMP_PORT: ${RABBITMQ_STOMP_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASS}
        FRONTEND_URL: ${FRONTEND_URL}
    networks:
        - meeting-team-network
  notification-service:
      container_name: notification-service
      image: hungtran679/mt-notification
      depends_on:
        - mysql-service
        - noti-broker
      ports: 
        - 8081:8081
      environment:
        DB_HOST: mysql-service
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_DATABASE: ${DB_DATABASE}
        NOTIBROKER_HOST: rabbitmq-service
        NOTIBROKER_PORT: ${RABBITMQ_AMQP_PORT}
        NOTIBROKER_USER: ${RABBITMQ_USER}
        NOTIBROKER_PASS: ${RABBITMQ_PASS}
      networks:
        - meeting-team-network
networks:
  meeting-team-network:
volumes:
  db:
      

      
