# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hungtran679/mt-frontend
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: false

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: API_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: backend
        key: API_ENDPOINT

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
  - host: frontend.local
    paths:
      - path: /
        pathType: Prefix
  tls:
    - hosts:
        - frontend.local
      secretName: tls-secret

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}