# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: false

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

configmap:
  enabled: true
  data:
    DB_DATABASE: chatboxdb
    DB_PORT: "3306"

env:
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: mysql
        key: DB_DATABASE
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql
        key: DB_PASS

pvc:
  enabled: true
  accessMode: ReadWriteOnce
  storage: 500Mi
  pvName: mysql-pv
  mountPath: /var/lib/mysql

service:
  type: ClusterIP
  port: 3306

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
