apiVersion: v2
name: stomp-broker
description: A Helm chart for meetingteam stomp-broker
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common