# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hungtran679/stomp-broker
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: false

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

configmap:
  enabled: true
  data:
    STOMPBROKER_PORT: "61613"

env:
  - name: RABBITMQ_DEFAULT_USER
    valueFrom:
      secretKeyRef:
        name: stomp-broker
        key: STOMPBROKER_USER
  - name: RABBITMQ_DEFAULT_PASS
    valueFrom:
      secretKeyRef:
        name: stomp-broker
        key: STOMPBROKER_PASS

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 15672
  additionalPorts:
    - name: stomp
      port: 61613

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: stomp-broker.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}